
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/**

steps:
   - name: build
     image: haskell:8.10-buster
     commands:
      - stack build
      - stack test
      - stack exec transcripts
