---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/drone
    - refs/pull/**
    - refs/tags/**

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      pull: true
      restore: true
      mount:
        - stack
        - parser-typechecker/stack
    volumes:
      - name: cache
        path: /cache

  - name: deps
    image: registry.digitalocean.com/unison-lang/haskell-builder:11
    volumes:
      - name: root_home
        path: /root
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - mkdir -p stack
      - stack --work-dir stack --stack-root $PWD/stack build --test --only-dependencies

  - name: cache-deps
    group: post-build
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - stack
        - parser-typechecker/stack
      when:
        event: push
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: registry.digitalocean.com/unison-lang/haskell-builder:11
    settings:
      mount:
        - stack
    commands:
      - stack --work-dir stack --stack-root $PWD/stack build
      - stack --work-dir stack --stack-root $PWD/stack test
      - stack --work-dir stack --stack-root $PWD/stack exec transcripts

  - name: cache-build
    group: post-build
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - stack
        - parser-typechecker/stack
      when:
        event: push
    volumes:
      - name: cache
        path: /cache

  - name: publish-build
    group: post-build
    image: registry.digitalocean.com/unison-lang/haskell-builder:11
    environment:
      VAULT_ADDR: "https://vault.unison-lang.org:8200"
    commands:
      - UCM=$(stack --work-dir stack --stack-root $PWD/stack path | awk '/local-install-root/{print $2}')/bin/unison
      - mkdir -p /tmp/ucm/ui
      - cp $UCM /tmp/ucm/ucm
      - export ARCHIVE=unison-${DRONE_BUILD_NUMBER}.tar.gz
      - wget -O/tmp/ucm.zip https://github.com/unisonweb/codebase-ui/releases/download/latest/unisonShare.zip
      - unzip -d /tmp/ucm/ui /tmp/ucm.zip
      - tar -c -z -f $ARCHIVE -C /tmp/ucm .
      - vault login -method=cert -client-cert=/root/host_crt.pem -client-key=/root/host_key.pem 2>&1 > /dev/null
      - which ssh
      - vault ssh -mode ca -role repo -ssh-executable=$(which ssh) repo@downloads.private.unison-lang.org dd of=upload/$ARCHIVE < $ARCHIVE
    volumes:
      - name: root_home
        path: /root
      
volumes:
    - name: cache
      host:
        path: /tmp/cache2
    - name: docker_sock
      host:
        path: /var/run/docker.sock

    - name: root_home
      host:
        path: /root
