
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/drone
    - refs/pull/**
    - refs/tags/**

steps:
   - name: build
     image: registry.digitalocean.com/stewcasa/haskell-build:1
     commands:
      - stack build
      - stack test
      - stack exec transcripts
