
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/drone
    - refs/pull/**
    - refs/tags/**

volumes:
  - name: cache
    host:
      path: /tmp/cache
    
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      pull: true
      restore: true
      mount:
        - stack
    volumes:
      - name: cache
        path: /cache

  - name: deps
    image: registry.digitalocean.com/stewcasa/haskell-build:3
    commands:
      - mkdir -p stack
      - stack --stack-root $PWD/stack build --test --only-dependencies

  - name: cache-deps
    group: post-build
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - stack
      when:
        event: push
    volumes:
      - name: cache
        path: /cache


  - name: build
    image: registry.digitalocean.com/stewcasa/haskell-build:3
    commands:
      - stack --stack-root $PWD/stack build
      - stack --stack-root $PWD/stack test
      - stack --stack-root $PWD/stack exec transcripts

  - name: cache-build
    group: post-build
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - stack
      when:
        event: push
    volumes:
      - name: cache
        path: /cache

volumes:
    - name: cache
      host:
        path: /tmp/cache
        
