
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/drone
    - refs/pull/**
    - refs/tags/**

volumes:
  - name: cache
    host:
      path: /tmp/cache
    
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      pull: true
      restore: true
      mount:
        - /drone/src/github.com/stew/unison/.stack
        - /drone/src/github.com/stew/unison/.stack-work
    volumes:
      - name: cache
        path: /cache

  - name: deps
    image: registry.digitalocean.com/stewcasa/haskell-build:2
    environment:
      STACK_ROOT: /drone/src/github.com/stew/unison/.stack
      STACK_WORK: /drone/src/github.com/stew/unison/.stack-work
    commands:
      - stack build --test --only-dependencies

  - name: cache-deps
    group: post-build
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /drone/src/github.com/stew/unison/.stack
        - /drone/src/github.com/stew/unison/.stack-work
      when:
        event: push
    volumes:
      - name: cache
        path: /cache


  - name: build
    image: registry.digitalocean.com/stewcasa/haskell-build:2
    environment:
      STACK_ROOT: /drone/src/github.com/stew/unison/.stack
      STACK_WORK: /drone/src/github.com/stew/unison/.stack-work
    commands:
      - stack build
      - stack test
      - stack exec transcripts

volumes:
    - name: cache
      host:
        path: /tmp/cache
        
